### ISSUE TITLE
Termination of unused channels

### ISSUE THREAD

**Issue by JoshuaLakin** [masl/Srift-Bot#9]
Idea:
When user is not responding to the verification channel, it should delete itself after a certain amount of time.

**Comment by maselelele** [comment]
Thanks for the idea, currently there is a message showing...

> You needed too long, please recreate your channel

So you have to go to the #srift-bot channel, react with a red dot, and then with a green dot.

How exactly do you imagine an improved version of the whole feature?

**Comment by JoshuaLakin** [comment]
The channel should delete itself after a certain amount of time when user is not responding. It’s more a lazy feature. Sure one could go into the sriftchannel and recreate it by hand, but it deleting itself automatically is  “more convenient”

**Comment by maselelele** [comment]
Alright, I will try to implement the this enhancement as soon as possible!
